# Generated by Django 3.1.1 on 2020-10-12 08:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loaner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.EmailValidator], verbose_name='Email')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaners', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
