# Generated by Django 3.1.1 on 2020-10-19 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Payment Amount')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('payment_type', models.CharField(choices=[('received', 'Received'), ('paid', 'Paid')], default='paid', max_length=10, verbose_name='Payment Type')),
                ('loaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loaner', verbose_name='Loaner')),
            ],
        ),
    ]
