# Generated by Django 3.1.1 on 2020-10-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, verbose_name='Token')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start Time')),
                ('expiry_time', models.DateTimeField(default=None, verbose_name='Expiry Time')),
            ],
        ),
    ]
