# Generated by Django 3.1.1 on 2020-10-16 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0002_usersession_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_token', models.CharField(max_length=256, verbose_name='Link Token')),
                ('expiry_time', models.DateTimeField(default=None, verbose_name='Expiry Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_password_link', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
